#
# This file generates the sidebar/toctree for all TileDB projects and should
# be copied to each project when it is updated.
#
# This file is originally from the RobotPy documentation project https://github.com/robotpy/robotpy-docs, licensed under
#

import os

def write_if_changed(fname, contents):

    try:
        with open(fname, 'r') as fp:
            old_contents = fp.read()
    except:
        old_contents = ''

    if old_contents != contents:
        with open(fname, 'w') as fp:
            fp.write(contents)

def generate_sidebar(conf, conf_api):

    do_gen = conf['on_rtd']
    version = conf['rtd_version']

    lines = [
        '', '.. DO NOT MODIFY! THIS PAGE IS AUTOGENERATED!', ''
    ]

    url_base = 'https://tiledb-inc-tiledb.readthedocs-hosted.com'
    lang = 'en'

    def toctree(name):
        lines.extend(['.. toctree::',
                      '    :caption: %s' % name,
                      '    :maxdepth: 1',
                      ''])

    def endl():
        lines.append('')

    def write(desc, link):
        if conf_api == 'tiledb':
            args = desc, link
        elif not do_gen:
            return
        else:
            args = desc, '%s/%s/%s/%s.html' % (url_base, lang, version, link)

        lines.append('    %s <%s>' % args)

    def write_api(project, desc, rst_page):
        if project != conf_api:
            if do_gen:
                args = desc, url_base, project, lang, version, rst_page
                lines.append('    %s API <%s/projects/%s/%s/%s/%s.html>' % args)
        else:
            args = desc, rst_page
            lines.append('    %s API <%s>' % args)

    #
    # Specify the sidebar contents here
    #

    toctree('Getting Started')
    write('Introduction', 'introduction')
    write('Installation', 'installation')
    write('Usage', 'usage')
    endl()

    toctree('API Reference')
    write_api('tiledb', 'C', 'c-api')
    write_api('tiledb', 'C++', 'c++-api')
    write_api('tiledb-py', 'Python', 'python-api')
    endl()

    write_if_changed('_sidebar.rst.inc', '\n'.join(lines))
